Update github_workflow_simplified.yml

diff --git a/.github/workflows/github_workflow_simplified.yml b/.github/workflows/github_workflow_simplified.yml
--- a/.github/workflows/github_workflow_simplified.yml
+++ b/.github/workflows/github_workflow_simplified.yml
@@ -1,91 +1,90 @@
 name: Build, Test and Deploy a .NET Core WebApi to Azure App Service
 
-env: # Change these settings when you need to
+env:
   ARTIFACT_NAME: WebApi
   DOTNET_CORE_VERSION: 9.0.x
   PUBLISH_DIRECTORY: "./out/publish"
+  PROJECT_ROOT: "ATIx1.4_AI-System-Integration-Datascience-LU1/MonitoringAPI"
+  SOLUTION_PATH: "${{env.PROJECT_ROOT}}/MonitoringAPI.sln"
+  PROJECT_PATH: "${{env.PROJECT_ROOT}}/MonitoringAPI/MonitoringAPI.csproj"
+  TEST_PROJECT_PATH: "${{env.PROJECT_ROOT}}/MonitoringAPI.Tests/MonitoringAPI.Tests.csproj"
+
 on:
   push:
     branches:
       - main
       - deployment 
       - master
-
-  # Allows you to run this workflow manually from the Actions tab.
   workflow_dispatch:
 
 jobs:
-  check: # checking if the secrets exist (src: https://stackoverflow.com/questions/72925899/github-actions-detect-if-secret-exists)
-      runs-on: ubuntu-latest
-      steps:
-        - name: "Check if AZURE_WEBAPP_NAME secret exists"
-          env: 
-            super_secret: ${{ secrets.AZURE_WEBAPP_NAME }}
-          if: ${{ env.super_secret == '' }}
-          run: 'echo "echo the secret \"AZURE_WEBAPP_NAME\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions\" to create it"; exit 1;'
-    
-        - name: "Check if AZURE_WEBAPP_PUBLISH_PASSWORD secret exists"
-          env: 
-            super_secret: ${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}
-          if: ${{ env.super_secret == '' }}
-          run: 'echo "echo the secret \"AZURE_WEBAPP_PUBLISH_PASSWORD\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions \" to create it"; exit 1;'
-    
-        - name: "Check if AZURE_WEBAPP_PUBLISH_USERNAME secret exists"
-          env: 
-            super_secret: ${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}
-          if: ${{ env.super_secret == '' }}
-          run: 'echo "echo the secret \"AZURE_WEBAPP_PUBLISH_USERNAME\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions\" to create it"; exit 1;'
-    
-        - name: "Check if WEBAPI_PROJECT_NAME secret exists"
-          env: 
-            super_secret: ${{ secrets.WEBAPI_PROJECT_NAME }}
-          if: ${{ env.super_secret == '' }}
-          run: 'echo "echo the secret \"WEBAPI_PROJECT_NAME\" has not been made; echo please go to \"settings \> Actions secrets and variables \> actions\" to create it"; exit 1;'
+  check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Check if AZURE_WEBAPP_NAME exists"
+        if: ${{ secrets.AZURE_WEBAPP_NAME == '' }}
+        run: echo "::error::Secret AZURE_WEBAPP_NAME is missing" && exit 1
         
+      - name: "Check if AZURE_WEBAPP_PUBLISH_PASSWORD exists"
+        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD == '' }}
+        run: echo "::error::Secret AZURE_WEBAPP_PUBLISH_PASSWORD is missing" && exit 1
+        
+      - name: "Check if AZURE_WEBAPP_PUBLISH_USERNAME exists"
+        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME == '' }}
+        run: echo "::error::Secret AZURE_WEBAPP_PUBLISH_USERNAME is missing" && exit 1
+        
+      - name: "Check if WEBAPI_PROJECT_NAME exists"
+        if: ${{ secrets.WEBAPI_PROJECT_NAME == '' }}
+        run: echo "::error::Secret WEBAPI_PROJECT_NAME is missing" && exit 1
+
   build:
     runs-on: ubuntu-latest
     needs: check
     steps:
-    - uses: actions/checkout@v4
-    
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v4
-      with:
-        dotnet-version: ${{env.DOTNET_CORE_VERSION}}
-
-    - name: Restore dependencies
-      run: dotnet restore ${{env.PROJECT_ROOT}}/MonitoringAPI.sln
+      - uses: actions/checkout@v4
       
-    - name: Build
-      run: dotnet build ${{env.PROJECT_ROOT}}/MonitoringAPI.sln --no-restore
-    
-    - name: Test
-      run: dotnet test ${{env.PROJECT_ROOT}}/MonitoringAPI.Tests/MonitoringAPI.Tests.csproj --no-build --verbosity normal
-    
-    - name: Publish
-      run: dotnet publish ${{env.PROJECT_ROOT}}/MonitoringAPI/MonitoringAPI.csproj --output ${{env.PUBLISH_DIRECTORY}} --configuration Release
-    - name: Publish Artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: ${{ env.ARTIFACT_NAME }}
-        path: ${{ env.PUBLISH_DIRECTORY}}
+      - name: Verify directory structure
+        run: |
+          echo "Project root: ${{env.PROJECT_ROOT}}"
+          ls -R ${{env.PROJECT_ROOT}}
+      
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: ${{env.DOTNET_CORE_VERSION}}
+
+      - name: Restore dependencies
+        run: dotnet restore ${{env.SOLUTION_PATH}}
+        
+      - name: Build
+        run: dotnet build ${{env.SOLUTION_PATH}} --no-restore
+      
+      - name: Test
+        run: dotnet test ${{env.TEST_PROJECT_PATH}} --no-build --verbosity normal
+      
+      - name: Publish
+        run: dotnet publish ${{env.PROJECT_PATH}} --output ${{env.PUBLISH_DIRECTORY}} --configuration Release
+      
+      - name: Publish Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ env.ARTIFACT_NAME }}
+          path: ${{ env.PUBLISH_DIRECTORY}}
 
   deploy:
     runs-on: ubuntu-latest
     needs: [check, build]
     steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ env.ARTIFACT_NAME }}
+          path: ${{ env.PUBLISH_DIRECTORY}}
 
-    - name: Download artifact from build job
-      uses: actions/download-artifact@v4
-      with:
-        name: ${{ env.ARTIFACT_NAME }}
-        path: ${{ env.PUBLISH_DIRECTORY}}
-
-     # Deploy to Azure Web apps
-    - name: 'Deploy to Azure App Service'
-      uses: azure/webapps-deploy@v3
-      with: 
-        app-name: ${{ env.AZURE_WEBAPP_NAME }}
-        publish-profile: <publishData><publishProfile profileName="${{secrets.AZURE_WEBAPP_NAME}} - Zip Deploy" publishMethod="ZipDeploy" publishUrl="${{ secrets.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net:443" userName="${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}" userPWD="${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}" destinationAppUrl="http://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
-        package: '${{ env.PUBLISH_DIRECTORY}}'
-        clean: true
+      - name: Deploy to Azure App Service
+        uses: azure/webapps-deploy@v3
+        with: 
+          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
+          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
+          package: ${{ env.PUBLISH_DIRECTORY}}
+          clean: true
